version: "3.8"
services:
  backend:
    build: ./packages/backend
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: rebuild
          path: ./packages/backend
          ignore:
            - _build
  frontend:
    build: ./packages/frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=http://localhost:4000
    develop:
      watch:
        - action: rebuild
          path: ./packages/frontend
          ignore:
            - node_modules/
            - static/
        - action: sync
          path: ./packages/frontend/static
          target: /server

