version: "4.8"
services:
  frontend:
    build: ./packages/frontend
    ports:
      - "3000:80"
    develop:
      watch:
        - action: rebuild
          path: ./packages/frontend
          ignore:
            - node_modules/
            - static/
        - action: sync
          path: ./packages/frontend/static
          target: /server

