version: "3.8"
services:
  backend:
    image: mandax/rescript-country-selector-backend:latest
    ports:
      - "4000:4000"
  frontend:
    image: mandax/rescript-country-selector-frontend:latest
    environment:
      - API_URL=http://ahrefs.afp.sh:4000
    ports:
      - "80:80"

